### ISSUE TITLE
Implement Internationalization (i18n)

### ISSUE THREAD

**Issue by hsribei** [dennisreimann/masquerade#1]
It would be nice to allow translations. Using an off-code format like gettext is even better for the amount of non-developer tools already available.

**Comment by hsribei** [comment]
I'm trying to find the time to do this myself, btw. Just added it here as a way of keeping track of feature wishes.

**Comment by dennisreimann** [comment]
Yeah, that would be great, go ahead :)

**Comment by dennisreimann** [comment]
This was brought in by djmaze with this commit: 78ce8ee85a78873ee0f40203614341bfd4d90ba6

Great work!
