### ISSUE TITLE
masquerade not reconginzied as a valid OpenID service

### ISSUE THREAD

**Issue by jippi** [dennisreimann/masquerade#12]
Hi,

I just installed masquerade on my server ( https://id.bonitet.dk ) and I'm trying to login at www.openid.net with my identity: https://id.bonitet.dk/Jippi - but it complains it's not a valid OpenID service.. the same error is reported by all other sites I'm trying to sign in with the OpenID 

Are i'm doing something wrong, or is the project not complete?

Thanks!

**Comment by jippi** [comment]
I have tried to use the "OpenID delegation" on my website www.bonitet.dk

When I do that, it comes a bit further, it actually shows the approve/decline of granting the site access to my details, but afterwards, openid.net reports:

132 OpenID Response: Protocol Error
Either the OpenID response parameters were invalid or the an error occurred during the OpenID check_authentication call.

and facebook reports:

Error while processing response
There was an error while processing the OpenID response. No OpenID information found at https://id.bonitet.dk/Jippi for method Auth_OpenID_discover

**Comment by jippi** [comment]
I have put the server into development mode, and now I get this error:

URI::InvalidURIError in ServerController#index

the scheme https does not accept registry part: *.newz.dk (or bad hostname?)

/usr/lib/ruby/1.8/uri/generic.rb:195:in `initialize'
/usr/lib/ruby/1.8/uri/http.rb:78:in`initialize'
/usr/lib/ruby/1.8/uri/common.rb:488:in `new'
/usr/lib/ruby/1.8/uri/common.rb:488:in`parse'
/home/masquerade/app/models/open_id_request.rb:15:in `from_trusted_domain?'
/home/masquerade/app/controllers/server_controller.rb:130:in`handle_checkid_request'
/home/masquerade/app/controllers/server_controller.rb:25:in `index'
/home/masquerade/app/controllers/server_controller.rb:22:in`index'

**Comment by djmaze** [comment]
Your SSL certificate is not trusted. I've entered your OpenID identity at https://openid.net/foundation/members/. The site says: 

109 Discovery: SSL Error
An SSL certificate validation or protocol level error occurred while performing discovery. 

Also, my Android phone complains when visiting your site. Seems like the certificate authority (PositiveSSL) is not trusted by all devices / services. You may need a "better" CA.

You could also try without https - that should work. You would have to change Masquerade's configuration then.

**Comment by jippi** [comment]
Hi, thanks for the quick reply.

I'm using a Comodo ssl cert, been using them on all kind of services for a long time without issues. 

I also found a bug by the way,

app/models/open_id_request.rb :: from_trusted_domain?

```
    begin
            host = URI.parse(parameters['openid.realm'] || parameters['openid.trust_root']).host
            APP_CONFIG['trusted_domains'].find { |domain| host.ends_with? domain }
    rescue URI::InvalidURIError
            false
    end
```

handles the issue with *.domain.com  requests

I'm going to try without ssl on the other issue

**Comment by jippi** [comment]
Okay, seem to have fixed the initial issue, openid.net now allows me to connect, I'm now presented with a login screen where my OpenID is prefilled: Your OpenID: https://id.bonitet.dk/Jippi

when I enter my password it just says "The login is incorrect or your account is not activated, yet."

The query that is invoked is:

```
SELECT * FROM "accounts" WHERE (login = E'https://id.bonitet.dk/Jippi' and enabled = 't' and activated_at IS NOT NULL) LIMIT 1
```

which clearly is wrong?  login is not the full url when I select from dbconsole, its jus 'Jippi'

I changed ApplicationController::extract_login_from_identifier to

```
openid_url.split('/').last
```

and it returns "JippI" as its supposed to (?)

however, it still complains about invalid user credentials even though the query

```
SELECT * FROM "accounts" WHERE (login = E'Jippi' and enabled = 't' and activated_at IS NOT NULL) LIMIT 1
```

returns a valid record when i do it from dbconsole

any ideas?

**Comment by jippi** [comment]
Also, now Facebook gives me:

OpenID signature error
The signature given by the OpenID provider did not match.

When I try to link it with my OpenID server  (using http://id.bonitet.dk/Jippi )

**Comment by jippi** [comment]
Hello,

It seems that I had to include a  SSLCACertificateFile in my apache ssl configuration, once I did that, and turned ssl back on, it just worked - facebook too

Guess there may be a bug somewhere with non-https since it didn't (and still doesnt) work with non-ssl and facebook.

Thanks!

**Comment by jippi** [comment]
Hmm, I still can't get it to work. when I'm promoted to login to verify the openid request, it just keeps sending me to the login screen - I can never actually reach the page where  I can approve the request..

**Comment by djmaze** [comment]
Hi Jippi,

I've taken the liberty to create a test account on your server ("testing"). I was also unable to login to a site. My profile page tells me my identity is http://id.bonitet.dk/testing. Did you set use_ssl to true in app_config.yml, for the production environment?

**Comment by jippi** [comment]
Hmm, I did, but I forgot I had changed the RailsEnv to development :o

let's see if it works now

**Comment by jippi** [comment]
(also, would be nice if it was possible to block / approve users from signing up to my openid broker) :)

**Comment by djmaze** [comment]
Yeah, you could create a feature request issue for that ;-)

**Comment by jippi** [comment]
Done, #13 :)

Thanks for the help!

**Comment by djmaze** [comment]
So, has this bug been resolved now?

**Comment by jippi** [comment]
sure has
