### ISSUE TITLE
possible to block / approve users from signing up to my openid broker

### ISSUE THREAD

**Issue by jippi** [dennisreimann/masquerade#13]
Hi,

I think it would be awsome if I could 

a) put the OpenID broker into "read-only" mode, where people can't sign up 
b) be able to require manual activation of new users on the broker (admin feature)
c) "a)" + generate invitation codes people can use to bypass the lock-down

Thanks! :)

**Comment by dennisreimann** [comment]
Getting masquerade ready for Rails 3 I want to switch from using restful_authentication to Device which has a lot of the mentioned functionality built-in.

**Comment by jippi** [comment]
Okay :)

I'm quite happy with Clearance ! :)
I even made a facebook connector too.. .and it got dead simple twitter / OAuth intigration

**Comment by dennisreimann** [comment]
Now that it's Rails 3 compatible I don't think it is necessary to bring in Devise, as the current approach (restful authentication) works well enough. If you'd still like to have this feature it would be great if you could implement it :)

**Comment by djmaze** [comment]
Thanks to @nougad, 
a) has now been implemented (see a9b300391c5c479c7130).
b) is half implemented (see 62ba5e320993e6d58548087434f6505913c4ced1).

**Comment by jimcavoli** [comment]
Implementing c) is tricky on a large scale without having a full-blown admin interface for Masquerade, which in my opinion, is way too heavy duty and unnecessary.
The best way I can think to do this would be to put a list of accounts allowed to generate invite codes into the config file, and having that option show if the provider is running in restricted-registration mode.
I could do this after polishing off the OmniAuth branch. Thoughts?

**Comment by dennisreimann** [comment]
In my opinion having an admin area where one could create/manage accounts would be the most transparent solution.
I think we should discuss that after Jim's migration to OmniAuth is done, as there are some more thoughts I have about making masquerade more modular.

**Comment by jimcavoli** [comment]
Agree. Let's hold this until #15 and the OmniAuth development is done; modularizing more of Masquerade sounds like a good thing...hopefully I can help get us off in a good direction and implement some of those thoughts!
