### ISSUE TITLE
problem with rpxnow and wordpress openid plugin

### ISSUE THREAD

**Issue by saten** [dennisreimann/masquerade#16]
wordpress reports this when trying to log in with my openid on masquerade

OpenID authentication failed: Server denied check_authentication

maybe this is not masquerade specific, and googling i've found a lot of similar problems
someone says it's php-openid library related
someone suggests it's ssl certificates related (i only have self signed at the moment)

is there any solution / reason on server side for this?

**Comment by dennisreimann** [comment]
I had this problem myself, but could find out where the issue actually is, because the error messages provided by wordpress were too unclear and from the logs it seemed like it should have worked.

**Comment by saten** [comment]
i can add that this seems to me not related to the ruby-openid library, since i can manage to log into wordpress with a sample openid created here:

http://openidenabled.com/ruby-openid/trunk/examples/user/pippo

**Comment by saten** [comment]
maybe this is useless:

apart from the ax data, the only other significant difference i can notice between what travels through the browser is this:

with masquerade

openid.claimed_id=http://login.sportbay.org/saten&
openid.identity=https://login.sportbay.org/saten&

with the example server on openidenabled they're the same, while here there's the extra 's' after 'http'

**Comment by saten** [comment]
ok, so it's ssl related (and my fault)
it works disabling the use of ssl in app_config.yml
i forgot to set that before moving into production, so i guess it should work once i set the correct values
i'll keep you informed if you want ;)

**Comment by dennisreimann** [comment]
Maybe this is also related to this issue with the ruby-openid gem:
http://github.com/openid/ruby-openid/issues#issue/1

**Comment by saten** [comment]
hi, today i've set up my ssl certificate and all works fine!
