### ISSUE TITLE
empty trusted_domains causes exception, 500 on attempted auth

### ISSUE THREAD

**Issue by pjjw** [dennisreimann/masquerade#17]
Just noting that if trusted_domains is empty, then we get a cute little exception instead of the anti-phishing page.

<code>Processing ServerController#index (for xxxxx at 2010-06-15 20:07:06) [GET]
  Parameters: {"openid.mode"=>"checkid_setup", "openid.ns.sreg"=>"http://openid.net/extensions/sreg/1.1", "openid.return_to"=>"https://xxxxxxx/sessions?_method=post
&open_id_complete=1", "openid.ns"=>"http://specs.openid.net/auth/2.0", "action"=>"index", "openid.sreg.optional"=>"fullname", "openid.identity"=>"xxxxxxx", "openid.ns.ax"=>"http://openid.net/srv/ax/1.0", "openid.sreg.required"=>"nickname,email", "openid.assoc_handle"=>"xxxxxxx", "controller"=>"serv
er", "openid.ax.mode"=>"fetch_request", "openid.realm"=>"xxxxxx", "openid.claimed_id"=>"xxxxxxx"}

NoMethodError (undefined method `find' for nil:NilClass):
  app/models/open_id_request.rb:17:in`from_trusted_domain?'
  app/controllers/server_controller.rb:130:in `handle_checkid_request'
  app/controllers/server_controller.rb:25
  app/controllers/server_controller.rb:22:in`index'
  /usr/lib/ruby/1.8/mongrel/rails.rb:76:in `process'
  /usr/lib/ruby/1.8/mongrel/rails.rb:74:in`synchronize'
  /usr/lib/ruby/1.8/mongrel/rails.rb:74:in `process'
  /usr/lib/ruby/1.8/mongrel.rb:159:in`process_client'
  /usr/lib/ruby/1.8/mongrel.rb:158:in `each'
  /usr/lib/ruby/1.8/mongrel.rb:158:in`process_client'
  /usr/lib/ruby/1.8/mongrel.rb:285:in `run'
  /usr/lib/ruby/1.8/mongrel.rb:285:in`initialize'
  /usr/lib/ruby/1.8/mongrel.rb:285:in `new'
  /usr/lib/ruby/1.8/mongrel.rb:285:in`run'
  /usr/lib/ruby/1.8/mongrel.rb:268:in `initialize'
  /usr/lib/ruby/1.8/mongrel.rb:268:in`new'
  /usr/lib/ruby/1.8/mongrel.rb:268:in `run'
  /usr/lib/ruby/1.8/mongrel/configurator.rb:282:in`run'
  /usr/lib/ruby/1.8/mongrel/configurator.rb:281:in `each'
  /usr/lib/ruby/1.8/mongrel/configurator.rb:281:in`run'
  /usr/lib/ruby/1.8/mongrel/command.rb:212:in `run'

Rendering /home/klang/sites/masquerade/public/500.html (500)
</code>

**Comment by dennisreimann** [comment]
Fix for empty trusted_domains. Closed by 85011c2bcf42b87d2efa304d87f8ce9c8c0b07d6

**Comment by pjjw** [comment]
Thanks!
