### ISSUE TITLE
NoMethodError on login

### ISSUE THREAD

**Issue by Chralu** [dennisreimann/masquerade#19]
Just after having created and activated a new account, I try to log in. It produces an internal error.
Logs shows that :

<pre>
NoMethodError (undefined method `yubico_identity?' for #Account:0xb6132598>):
  app/models/account.rb:89:in `authenticated?'
  app/models/account.rb:70:in `authenticate'
  app/controllers/sessions_controller.rb:10:in `create'
  passenger (2.2.15) lib/phusion_passenger/rack/request_handler.rb:92:in `process_request'
  passenger (2.2.15) lib/phusion_passenger/abstract_request_handler.rb:207:in `main_loop'
  passenger (2.2.15) lib/phusion_passenger/railz/application_spawner.rb:441:in `start_request_handler'
  passenger (2.2.15) lib/phusion_passenger/railz/application_spawner.rb:381:in `handle_spawn_application'
  passenger (2.2.15) lib/phusion_passenger/utils.rb:252:in `safe_fork'
  passenger (2.2.15) lib/phusion_passenger/railz/application_spawner.rb:377:in `handle_spawn_application'
  passenger (2.2.15) lib/phusion_passenger/abstract_server.rb:352:in `__send__'
  passenger (2.2.15) lib/phusion_passenger/abstract_server.rb:352:in `main_loop'
  passenger (2.2.15) lib/phusion_passenger/abstract_server.rb:196:in `start_synchronously'
  passenger (2.2.15) lib/phusion_passenger/abstract_server.rb:163:in `start'
  passenger (2.2.15) lib/phusion_passenger/railz/application_spawner.rb:222:in `start'
  passenger (2.2.15) lib/phusion_passenger/spawn_manager.rb:253:in `spawn_rails_application'
  passenger (2.2.15) lib/phusion_passenger/abstract_server_collection.rb:126:in `lookup_or_add'
  passenger (2.2.15) lib/phusion_passenger/spawn_manager.rb:247:in `spawn_rails_application'
  passenger (2.2.15) lib/phusion_passenger/abstract_server_collection.rb:80:in `synchronize'
  passenger (2.2.15) lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
  passenger (2.2.15) lib/phusion_passenger/spawn_manager.rb:246:in `spawn_rails_application'
  passenger (2.2.15) lib/phusion_passenger/spawn_manager.rb:145:in `spawn_application'
  passenger (2.2.15) lib/phusion_passenger/spawn_manager.rb:278:in `handle_spawn_application'
  passenger (2.2.15) lib/phusion_passenger/abstract_server.rb:352:in `__send__'
  passenger (2.2.15) lib/phusion_passenger/abstract_server.rb:352:in `main_loop'
  passenger (2.2.15) lib/phusion_passenger/abstract_server.rb:196:in `start_synchronously'

Rendering /srv/http/rails/masquerade/public/500.html (500)
</pre>

**Comment by djmaze** [comment]
Seems like you did not run all migrations. The field "yubico_identity" was added in db/migrate/004_add_yubico_identity_to_account.rb.

Please make sure to run all migrations before starting your app for the first time ("rake db:migrate").

**Comment by Chralu** [comment]
Actually, I ran the "rake db:migrate RAILS_ENV=production" command, because I plan to use it in a production environment.

update : You're right, I just re-migrate on a clean database, and an error occurs on migration :

<pre>
==  AddTypeIdentifierToReleasePolicies: migrating =============================
-- add_column(:release_policies, :type_identifier, :string)
   -> 0.2084s
-- remove_index(:release_policies, {:column=>[:site_id, :property]})
   -> 0.2126s
-- add_index(:release_policies, [:site_id, :property, :type_identifier], {:name=>:unique_property, :unique=>true})
rake aborted!
An error has occurred, all later migrations canceled:

undefined method `length' for :unique_property:Symbol
</pre>

**Comment by djmaze** [comment]
Could you try replacing the symbol :unique_property in the migration with the string 'unique_property' and running migrate again?

**Comment by Chralu** [comment]
It works perfectly that way.
 Thanks a lot for helping @djmaze
