### ISSUE TITLE
Unable to authorize pending verification requests

### ISSUE THREAD

**Issue by cwjohnston** [dennisreimann/masquerade#2]
Masquerade shows a verification request from my consumer but there are no actions available to me on the "decide" page. Am I missing something?

relevant screenshot: http://i.imgur.com/TpOvF.png

**Comment by dennisreimann** [comment]
It seems your account doesn't have any personas defined. Is that so?

**Comment by cwjohnston** [comment]
You're right, I didn't have a persona defined. After defining a persona I am able to approve the request from my consumer. Thanks!

**Comment by dennisreimann** [comment]
Ok, nevertheless this should be stated in the interface…

**Comment by dennisreimann** [comment]
Okay, this is finally fixed: 6d12153597c6207fa4daa6333c2dd8bf7a9e38a9
