### ISSUE TITLE
Verification issue

### ISSUE THREAD

**Issue by resistorsoftware** [dennisreimann/masquerade#20]
Hi, I post a gist with the backend of what happen when I try and authenticate my account:
https://gist.github.com/733346

I send up being asked to trust the root, and then validate returns with:
Verification of http://localhost:3000/dlazar failed: Unexpected parameter (not on return_to): 'action'=nil)

I am not sure what is wrong. The account  http://localhost:3000/dlazar exists. I checked it in the DB. Seems OK... any idea what might be the problem? Running Rails3 and all the included tests pass. Only mod I made so far was to use PostgreSQL and MySQL...

**Comment by dennisreimann** [comment]
Fixed path params problem. Closed by 8ebd16871396432c477c4f3efdba768d007d1c47

**Comment by dennisreimann** [comment]
This is fixed now, though it was just a problem in the consumer example code... it should have worked with other sites. Can you verify that this works for you?
