### ISSUE TITLE
Unable to add trusted sites

### ISSUE THREAD

**Issue by cwjohnston** [dennisreimann/masquerade#3]
When I click on the "my trusted sites" tab there's nothing to click on for managing trusted sites.

**Comment by dennisreimann** [comment]
You can't add trusted sites like this... once you got a verification request going, you can decide to always trust the site in the future and afterwards it will be managable in the "my trusted sites" area.

**Comment by cwjohnston** [comment]
I have approved verification requests from a particular consumer multiple times, but I have yet to see it to show up under "my trusted sites."
