### ISSUE TITLE
Unable to create OpenID in masquerade.

### ISSUE THREAD

**Issue by kench** [dennisreimann/masquerade#8]
I have cloned a copy of the repository and installed it on my own server, but when I try to create an OpenID, I get a 500 error and the following output in the log:

Processing ApplicationController#create (for REDACTED at 2010-03-10 15:49:08) [POST]
  Parameters: {"commit"=>"Signup", "action"=>"create", "authenticity_token"=>"[FILTERED]", "account"=>{"password_confirmation"=>"[FILTERED]", "password"=>"[FILTERED]", "login"=>"ken", "email"=>"ken@REDACTED"}, "controller"=>"accounts"}

ActionView::MissingTemplate (Missing template exception_notifier/exception_notification.erb in view path app/views):
  /opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
  /opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/1.8/webrick/httpserver.rb:65:in`run'
  /opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
  /opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/1.8/webrick/server.rb:162:in`start'
  /opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
  /opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/1.8/webrick/server.rb:95:in`start'
  /opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/1.8/webrick/server.rb:92:in `each'
  /opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/1.8/webrick/server.rb:92:in`start'
  /opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/1.8/webrick/server.rb:23:in `start'
  /opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/1.8/webrick/server.rb:82:in`start'

Rendering /var/apps/masquerade/public/500.html (500)

**Comment by dennisreimann** [comment]
Which branch are you using? I can't confirm that with the current master...

**Comment by kench** [comment]
I'm using master.  I'll try deleting my local copy and reinstalling to see it if it fixes the problem.

**Comment by kench** [comment]
Still not working.  When I submit the OpenID creation form, I get a 500 error on nginx.  I can replicate it using script/server in production, but not in development.

**Comment by kench** [comment]
Found the problem.  Misconfigured mail server in app_config.yml.

**Comment by dennisreimann** [comment]
Ok, I'm closing this.
