### ISSUE TITLE
cannot fetch ax with openid authentication plugin

### ISSUE THREAD

**Issue by leiwan5** [dennisreimann/masquerade#9]
I followed http://railscasts.com/episodes/170-openid-with-authlogic and http://stackoverflow.com/questions/787894/ruby-openid-requiring-email-address-from-openid-provider.
User can login with masquerade openid url, but the program cannot fetch any ax.
I did a test with my google openid url, it can get my email address.

Here is my user model:

<pre>
class User < ActiveRecord::Base
  acts_as_authentic do |c|
    c.validate_login_field = false
    c.validate_email_field = false
    c.openid_required_fields = [:email, "http://axschema.org/contact/email"]
  end

  def map_openid_registration(reg)
    emails = reg['http://axschema.org/contact/email']
    self.email ||= (emails.first if respond_to?(:email) && !emails.blank?)
  end
end
</pre>

The request uri is here:
http://yc:3000/server?openid.assoc_handle=%7BHMAC-SHA1%7D%7B4b9ee0f3%7D%7BKpMniA%3D%3D%7D&openid.ax.mode=fetch_request&openid.ax.required=ext0&openid.ax.type.ext0=http%3A%2F%2Faxschema.org%2Fcontact%2Femail&openid.claimed_id=http%3A%2F%2Fyc%3A3000%2Fdanielking&openid.identity=http%3A%2F%2Fyc%3A3000%2Fdanielking&openid.mode=checkid_setup&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.ns.ax=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ns.sreg=http%3A%2F%2Fopenid.net%2Fextensions%2Fsreg%2F1.1&openid.realm=http%3A%2F%2Fyc%3A3001%2F&openid.return_to=http%3A%2F%2Fyc%3A3001%2Fusers%3Ffor_model%3D1%26_method%3Dpost%26open_id_complete%3D1&openid.sreg.required=email

**Comment by dennisreimann** [comment]
Which version are you using and did you ensure that you got the attribute_mappings in your app_config.yml ? I moved them out of the persona and into the configuration with this commit: 09f2a8671a684759f1d81a52cd41ea0a82c8c592

You can use the app_config.yml.example as a reference:
http://github.com/dbloete/masquerade/blob/master/config/app_config.yml.example

**Comment by leiwan5** [comment]
I use the latest version, the "git clone" one. Most settings of app_config.yml are copied from app_config.yml.example.

**Comment by leiwan5** [comment]
There are two email addresses, one is in "Profile" and the other is in "Public persona". I wondered which email will be used for ax? Both of them ware not empty when testing.

**Comment by dennisreimann** [comment]
I don't know how authlogic handles OpenID, but you can try the example provided by the consumer controller (just go to /consumer and make a request, after that have a look at the code of the controller) or have a look at the integration test for the OpenID use cases. For me the tests are running fine - do they fail on your machine?

**Comment by dennisreimann** [comment]
Hey Daniel, did you find out anything concerning this issue?
